### ISSUE TITLE
[FIX] - TERRAFORM DESTROY (ON CALL) WORKFLOW

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/stuttgart-things#171]
IF TERRAFORM OPTION = DESTROY AND NOTHING TO DESTROY = FAILED

**Comment by sina-schlatter** [comment]
Logik: Execute Terraform wird für merge nicht benötigt (so kann Ordner auch gelöscht werden, wenn VM bereits destroyed)
https://github.com/stuttgart-things/stuttgart-things/commit/0f7a862923fd38ec82c3bc2888f61df02fe3024d

**Comment by patrick-hermann-sva** [comment]
implemented
